- bayesianbandits/__init__.py
- bayesianbandits/_basebandit.py
- docs/generated/_autosummary/bayesianbandits.DelayedRewardException.rst
- docs/generated/_autosummary/bayesianbandits.NormalInverseGammaRegressor.rst
- docs/generated/_autosummary/bayesianbandits.NormalRegressor.rst
- tests/test_basebandit.py
> Throw exception when `unique_id` is reused

- bayesianbandits/_basebandit.py
- setup.cfg
- tests/test_basebandit.py
> Better error handling when `unique_id` is unknown to `update`

- bayesianbandits/_estimators.py
- bayesianbandits/_sparse_bayesian_linear_regression.py
- tests/test_estimators.py
The tests check that all existing methods return the same values whether or not `sparse=True`, while also checking that `cov_inv_` is a sparse matrix when `spare=True`
> [FEAT] Sparse Bayesian Linear Regression with both unknown mean and variance

- bayesianbandits/_sparse_bayesian_linear_regression.py
- poetry.lock
- pyproject.toml
> [RELEASE] v0.5.0

- bayesianbandits/_estimators.py
> FIX: if the learner has not been fit, `decay` returns without doing anything

- bayesianbandits/_basebandit.py
> FIX: prevent pickled bandits from before version 0.4.6 from throwing errors in 0.4.6+

- .readthedocs.yaml
- bayesianbandits/_estimators.py
- bayesianbandits/_sparse_bayesian_linear_regression.py
- poetry.lock
- pyproject.toml
- tests/test_normal_estimators.py
- tests/test_sparse_bayesian_linear_regression.py
Also adds a bunch of tests for linear models.
> [DOCS] Fixes errors in the documentation build process

- bayesianbandits/_basebandit.py
- bayesianbandits/_typing.py
- tests/test_api.py
- tests/test_normal_estimators.py
- tests/test_solver_detection.py
This pull request fixes the type hints in the code and removes unused imports. It also adds test cases for exception handling.
> Fix type hints and remove unused imports

- bayesianbandits/_policy_decorators.py
- bayesianbandits/api.py
- pyproject.toml
- tests/test_api.py
- tests/test_arm.py
- tests/test_basebandit.py
This pull request reverts the previous change made to the Thompson sampling algorithm. The update version in pyproject.toml is also updated to 0.6.1.
> Revert Thompson sampling change

- bayesianbandits/__init__.py
- bayesianbandits/_estimators.py
- bayesianbandits/api.py
- docs/index.rst
This pull request updates the API references in the documentation to include the correct citation format and removes the note about the library being under development.
> Update API references

- bayesianbandits/api.py
> Agent API now shares random state between arms

- bayesianbandits/_estimators.py
- tests/test_estimators.py
> Gamma regressor `sample` output dimensions are inconsistent with normal regressors

- bayesianbandits/api.py
1. Summarize arms
2. Postprocess
3. Argmax
This will make it much simpler to implement masked policies.
> [REFACTOR] Break policies into three steps:

- .github/workflows/ci.yml
- .github/workflows/matrix_test.yml
- poetry.lock
- pyproject.toml
> Python 3.13 compatibility, drop 3.9 support

- bayesianbandits/api.py
This PR enhances the bandit architecture by routing both arm selection AND reward updates through the policy, enabling new families of bandit algorithms.
* Added an update method to the PolicyProtocol interface
* Created a PolicyDefaultUpdate mixin that provides the standard update behavior
* Modified ContextualAgent.update to delegate to the policy's update method
* Updated existing policy classes to inherit from PolicyDefaultUpdate
1. Enables adversarial bandits (e.g., Exp3)
* Selection: Policy calculates arm selection probabilities
* Update: Policy applies importance sampling weights (1/selection_probability) during updates
* Having both operations flow through the policy ensures consistent probability calculations
2. Enables metric-space/Lipschitz bandits
* Selection: Policy can …
> FEAT: Add update method to PolicyProtocol and implement default update in policy classes

- bayesianbandits/_estimators.py
- tests/test_estimators.py
Introduce support for sample weights in the GammaRegressor to enhance model fitting and prediction capabilities. Update the documentation to reflect the new functionality and include tests to ensure proper handling of sample weights.
Fixes #142
> Add sample_weight handling to GammaRegressor

- bayesianbandits/_arm.py
- bayesianbandits/_typing.py
- bayesianbandits/api.py
- uv.lock
> Expore sample_weight in Arm class

- bayesianbandits/api.py
- bayesianbandits/policies/_exp3a.py
- tests/test_api.py
- tests/test_exp3a.py
Implement separation of sampling and decision-making in policies to optimize performance for agents using custom sampling strategies. Add tests for EpsilonGreedy and EXP3A algorithms to ensure correct functionality with top_k selection, including scenarios with zero probabilities.
> Separate sampling and decisioning in policies with tests for top_k selection

- bayesianbandits/_arm.py
- bayesianbandits/api.py
- tests/test_arm.py
- tests/test_batch_reward_examples.py
Reduce some complexity via helper functions, improve documentation.
> Refactor and enhance batch reward function handling

- bayesianbandits/api.py
When features are shared across arms, only decay once
> Fix batch reward function handling in LipschitzContextualAgent
